
[source.crates-io]
replace-with = "vendored-sources"

[source."https://github.com/bjorn3/rust-ar.git"]
git = "https://github.com/bjorn3/rust-ar.git"
branch = "do_not_remove_cg_clif_ranlib"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
